-- MySQL Script generated by MySQL Workbench
-- Sat Jul 29 11:36:42 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema weather
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `weather` ;

-- -----------------------------------------------------
-- Schema weather
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `weather` DEFAULT CHARACTER SET utf8 ;
USE `weather` ;

-- -----------------------------------------------------
-- Table `weather`.`predictions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weather`.`predictions` ;

CREATE TABLE IF NOT EXISTS `weather`.`predictions` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `weather_code` INT NOT NULL,
  `temperature` VARCHAR(10) NOT NULL,
  `humidity` VARCHAR(10) NOT NULL,
  `prediction_date` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `weather`.`posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weather`.`posts` ;

CREATE TABLE IF NOT EXISTS `weather`.`posts` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `prediction_id` BIGINT NOT NULL,
  `weather_code` INT NOT NULL,
  `text` VARCHAR(100) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `weather`.`post_likes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weather`.`post_likes` ;

CREATE TABLE IF NOT EXISTS `weather`.`post_likes` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `post_id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  `is_liked` TINYINT(1) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `weather`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weather`.`users` ;

CREATE TABLE IF NOT EXISTS `weather`.`users` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nickname` VARCHAR(10) NOT NULL,
  `uuid` VARCHAR(100) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
