server:
  port: 9000
  context-path: /

spring:
  jackson:
    property-naming-strategy: com.fasterxml.jackson.databind.PropertyNamingStrategy.SnakeCaseStrategy
    deserialization.fail-on-unknown-properties: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    open-in-view: false

---

spring:
  profiles: local
  datasource:
    username: test
    password: test
    url: jdbc:mysql://localhost/weather?useUnicode=true&characterEncoding=utf8&useSSL=false

